### ISSUE TITLE
RuntimeError: expected scalar type Half but found Float

### ISSUE THREAD

**Issue by yfji** [taotaonice/FaceShifter#14]
I train AEI net and the error is "expected scalar type Half but found Float"
I found this error is caused by L_id. After I delete L_id from lossG the error becomes "CUDA error: an illegal memory access was encountered"
`with amp.scale_loss(lossG, opt_G) as scaled_loss:
            scaled_loss.backward()`

**Comment by taotaonice** [comment]
I have never met this situation

**Comment by ocastan** [comment]
Not sure if it's the same problem but I had a similar error (LongTensor instead of FloatTensor). Since I'm using conda, I made it uninstall pytorch, cudatoolkit, nvidia-apex and cudnn, and I just asked pytorch and nvidia-apex re-installation, using the conda-forge channel, and the error disappeared. I hope it will help

**Comment by wvinzh** [comment]
@yfji Have you solved this error? I meat the same error

**Comment by yfji** [comment]
@wvinzh Not yet. I have implemented the algorithm myself, but the results are far from the paper.

**Comment by cisspbru** [comment]
Y

> I train AEI net and the error is "expected scalar type Half but found Float"
> I found this error is caused by L_id. After I delete L_id from lossG the error becomes "CUDA error: an illegal memory access was encountered"
> `with amp.scale_loss(lossG, opt_G) as scaled_loss: scaled_loss.backward()`

Try to install  Pytorch with Conda, it's should help, 
"CUDA error: an illegal memory access was encountered" - decrease your batch size
